name: Release Charm to Edge and Publish Libraries

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Charm and Libraries
    uses: canonical/observability/.github/workflows/charm-release.yaml@v1
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
    with:
      charm-path: charm
      provider: microk8s
      default-track: "1.19"
      charmcraft-channel: "3.x/stable"
